BCDevOps/openshift-developer-tools

bin/ocFunctions.inc

 Add support for creating parameter files for image stream only build configurations

---

bin/compDeployments.sh
bin/genDepls.sh

Supports the processing of deployment configurations generated by override scripts.

Add support for processing additional deployment configuration files.

---

bin/compBuilds.sh
bin/compDeployments.sh
bin/genBuilds.sh
bin/genPipelineParams.sh
bin/genTemplateParams.sh
bin/ocFunctions.inc

- template param generation.
- build and deployment configuration generation.

 Add support for profiles.

---

bin/compDeployments.sh
bin/ocFunctions.inc
bin/settings.sh

- Move deployment config scripts into shared include file.

Refactor scripts.

---

bin/ocFunctions.inc
bin/runInContainer.sh

- removeFromList
- runInContainer

Add shared functions

---

bin/README.md
bin/ocFunctions.inc

Fix issue with white-spaces when generating parameter files

---

bin/assignRole.sh
bin/ocFunctions.inc

- with batch project assignment support.

Add an assign role script

---

bin/README.md

Added documentation for the problem encountered when using the mawk implementation of awk on Kali Linux. Also fixed a few minor typos.

Documented problems with Linux mawk.

---

bin/ocFunctions.inc

- Get the first "Running" pod by default.

Update getPodName functions

---

bin/ocFunctions.inc

Add listDatabases and getRecordCounts functions

---

bin/ocFunctions.inc

Integrate disk usage info into getRecordCounts

---

bin/overrides.inc

- The base script for all overrides.sh script implementations.
- Helps eliminate code duplication and cleans up overrides.sh script implementations.

Add overrides.inc

---

bin/ocFunctions.inc

- Lists a project's build configurations and their git references in a convenient column format.

Add listBuildRefs function

---

bin/compDeployments.sh
bin/ocFunctions.inc

Add support for passing configuration variables into override scripts

---

bin/compDeployments.sh
bin/ocFunctions.inc

Fix bug when encountering spaces in param values

---

bin/README.md

I stubbed my toe on this a couple times now, best to just fix it for others.

Update to result of cloned project name

---

bin/ocFunctions.inc

Fix echoError

---

bin/ocFunctions.inc

- A space delimited list of the templates (without file extensions) to include with processing.

Add support for specifying an include_templates list.

---

bin/ocFunctions.inc
bin/settings.sh

- Add support for global commands.
- Add `listProfiles` and `profileDetails` global commands.

Add some global profile management commands.

---

bin/ocFunctions.inc

Fix bug in deployConfigs and deployBuildConfigs

---

bin/ocFunctions.inc

Fix another bug in deployConfigs

---

bin/compDeployments.sh
bin/overrides.inc

Add support for generating configMaps from .env files

---

bin/genPipelineParams.sh

Ensure genPipelineParams.sh respects SKIP_PIPELINE_PROCESSING setting.

---

bin/ocFunctions.inc

Support override of `resourceSuffix` in getRecordCounts

---

bin/ocFunctions.inc

- Ensure the pull secret gets registered with the service accounts in the same environment in which the secret is created.

Fix pull secret registration

---

bin/formatConfigurationTemplates.sh
bin/ocFunctions.inc
bin/settings.sh

- To convert ocp configuration files from json to yaml.

Add formatConfigurationTemplates.sh script

---

bin/ocFunctions.inc

Add support for detecting NSP build configurations.

---

bin/ocFunctions.inc

Signed-off-by: wadeking98 <wkingnumber2@gmail.com>
request review from @esune and @WadeBarnes

added "Deployment" to deployment template filters

---

bin/genTemplateParams.sh
bin/settings.sh

Signed-off-by: Emiliano Suñé <emiliano.sune@gmail.com>

Update APPLICATION_DOMAIN_POSTFIX for OCP4

---

bin/ocFunctions.inc

Fix to `getRecordCounts` to support Postgres 12

---

bin/settings.sh

Add listBuildRefs to the list of global commands.

---

bin/processPipelines.sh

Add support for running processPipelines.sh on it's own.

---

bin/getDids.inc
bin/getDids.sh

- Created as separate files since these scripts are use case specific.

Add scripts for scanning for OCP for Hyperledger Indy/Aries DIDs

---

bin/getDids.inc

Add project display name

---

bin/ocFunctions.inc

Update listBuildRefs to support fully qualified namespaces

---

bin/ocFunctions.inc

Add cronjob to the list of resources used to detect a dc

---

bin/ocFunctions.inc
bin/overrides.inc

Fix --dry-run deprecation warnings.

---

bin/getDids.inc

- Add support for scanning the CANdy and BCovrin networks.

Refactor and update getDids code

---

bin/overrides.inc

- Provides a consistent method of generating a combined config map for configuration profiles.

Add support for generating a config map for a profile
